### ISSUE TITLE
Each pair of POCP values is calculated twice

### ISSUE THREAD

**Issue by fujch7** [hoelzer/pocp#1]
Hi developer,

Thanks for the amazing tools. It makes the task more convenient.

But I found that each pair of POCP values will be calculated twice, which doubles the time consumed.

Could you please help to resolve this problem?

**Comment by hoelzer** [comment]
hI!

Thanks and I am happy that these scripts are of further usage! 

You are right, I did not invest much development time and thus just calculate all pairwise comparisons. However, should be relatively easy to change this and reduce the compute time. I will look into it asap.

**Comment by hoelzer** [comment]
@fujch7 I checked the code and I think everything is working as intended. 

See: http://jb.asm.org/content/196/12/2210.full

> POCP. The conserved proteins between a pair of genomes were determined by aligning all the protein
> sequences of one genome (query genome) with all the protein sequences of another genome using the
> BLASTP program. Proteins from the query genome were considered conserved when they had a BLAST
> match with an E value of less than 1e−5, a sequence identity of more than 40%, and an alignable region
> of the query protein sequence of more than 50%. For a pair of genomes, each genome was used as the
> query genome to perform the BLASTP search. The number of conserved proteins in each genome of strains
> being compared was slightly different because of the existence of duplicate genes (paralogs). The percentage
> of conserved proteins (POCP) between two genomes was calculated as [(C1 + C2)/(T1 + T2)] · 100%, where C1 and
> C2 represent the conserved number of proteins in the two genomes being compared, respectively, and T1 and T2
> represent the total number of proteins in the two genomes being compared, respectively. In theory, the POCP
> value can vary from 0% to 100%, depending on the similarity of the protein contents of two genomes.

So for two species X and Y we actually have to do the blast comparisons 

X vs Y
and 
Y vs X

due to duplicated genes (paralogs). Imagine X has paralogs A1 and A2 and Y only has one copy A. 

When we compare X vs Y we will blast A1 against A and A2 against A. We will increase X_c (the counter for homologous genes) by 2 because we found A1 and A2 in the protein set of Y. When we compare Y vs X we will blast A against A1 and A against A2. We will increase Y_c by 1 because we now found A in the protein set of X.

Thus, we get slightly different countings for both comparisons. For example:

```
Cga_08-1274-3.faa:	Found 853 matches with an E value of less than 1.0e-05, a sequence identity of more than 40.0%, and an alignable region of the query protein sequence of more than 50.0%.
Cps_6BC.faa:	Found 855 matches with an E value of less than 1.0e-05, a sequence identity of more than 40.0%, and an alignable region of the query protein sequence of more than 50.0%.
```    

It makes no sense to do two (or any) blast runs for X vs X (so when we compare the protein set of the same genome), but this was just easier to implement and the computational overhead should be marginal.

**Comment by fujch7** [comment]
Thank you for your patience. Actually, this script will calculate each POCP value for twice. For strain X and Y in the same input folder, X as first and Y as second, pocp value will be calculated after blast X vs Y and Y vs X. After that, Y as first and X as second, pocp value will be calculated after blast Y vs X and X vs Y. See the result below, two identical POCP values were calculated.

`##################################
## P.O.C.P Blaster 
##################################

Start:	2020-09-10 11:24:27 +0800

Species 1:	Luteibacter_sp_329MFSha_GCA_900111665.1_prodigal_protein.faa
Species 2:	Dyella_halodurans_DHOG02_T_prodigal_protein.faa
Write output: output/0827faa/results//Dyella_halodurans_DHOG02_T_prodigal_protein-vs-Luteibacter_sp_329MFSha_GCA_900111665.1_prodigal_protein

Make blast databases...
	Done for Dyella_halodurans_DHOG02_T_prodigal_protein.faa.
	Done for Luteibacter_sp_329MFSha_GCA_900111665.1_prodigal_protein.faa.
Run Blastp...
	Dyella_halodurans_DHOG02_T_prodigal_protein.faa:	Found 2394 matches with an E value of less than 1.0e-05, a sequence identity of more than 40.0%, and an alignable region of the query protein sequence of more than 50.0%.
	Luteibacter_sp_329MFSha_GCA_900111665.1_prodigal_protein.faa:	Found 2353 matches with an E value of less than 1.0e-05, a sequence identity of more than 40.0%, and an alignable region of the query protein sequence of more than 50.0%.


C1:	2394
C2:	2353

T1:	4160
T2:	3645

POCP = [(C1+C2)/(T1+T2)]*100% = 60.82

End:	2020-09-10 11:26:42 +0800`
`##################################
## P.O.C.P Blaster 
##################################

Start:	2020-09-10 14:26:21 +0800

Species 1:	Dyella_halodurans_DHOG02_T_prodigal_protein.faa
Species 2:	Luteibacter_sp_329MFSha_GCA_900111665.1_prodigal_protein.faa
Write output: output/0827faa/results//Luteibacter_sp_329MFSha_GCA_900111665.1_prodigal_protein-vs-Dyella_halodurans_DHOG02_T_prodigal_protein

Make blast databases...
	Done for Luteibacter_sp_329MFSha_GCA_900111665.1_prodigal_protein.faa.
	Done for Dyella_halodurans_DHOG02_T_prodigal_protein.faa.
Run Blastp...
	Luteibacter_sp_329MFSha_GCA_900111665.1_prodigal_protein.faa:	Found 2353 matches with an E value of less than 1.0e-05, a sequence identity of more than 40.0%, and an alignable region of the query protein sequence of more than 50.0%.
	Dyella_halodurans_DHOG02_T_prodigal_protein.faa:	Found 2394 matches with an E value of less than 1.0e-05, a sequence identity of more than 40.0%, and an alignable region of the query protein sequence of more than 50.0%.


C1:	2353
C2:	2394

T1:	3645
T2:	4160

POCP = [(C1+C2)/(T1+T2)]*100% = 60.82

End:	2020-09-10 14:28:40 +0800`

**Comment by hoelzer** [comment]
Uh, you're right! It's too long that I looked into the script. But this makes no sense, yes. Thanks for the example, I will have a look again

**Comment by hoelzer** [comment]
Can you @fujch7 please try again? I pushed changes directly to the master branch so please just update (`git pull`) your pocp folder or clone the repository again.

**Comment by fujch7** [comment]
I clone it again, and it will still calculate the value twice.

**Comment by hoelzer** [comment]
Hi @fujch7 I found the problem. I checked it now with a minimal example and for me now each pairwise comparison between the same two species is only done once. 

I will do a release of this updated version v1.0.1 as well. 

Thanks for your help in improving this small script for POCP calculations! 

best
martin
