### ISSUE TITLE
How to compare one single genome A with multiple genomes(n>50)?

### ISSUE THREAD

**Issue by liuqian666** [hoelzer/pocp#2]
Hello! 
I have one genome A and many reference genomes (download from Genbank), and the number of reference genomes is 110.
If I do the command './pocp.rb example/ example/results/ 2', it will take too much time to compare with each other.
So, do you know how to adjust the command to solve the problem? 
Thank you very much!

**Comment by hoelzer** [comment]
Hi! Ah okay, so you don't want to do a pairwise all-vs-all comparison. 

Let me check, I think this should be doable with some small change. 

best

**Comment by hoelzer** [comment]
@liuqian666 srry for the late reply, I just found some time to look into this. 

```
cd pocp
git pull origin master
./pocp.rb example/ example/results/ 2 Cav_10DC88.faa
```

should be the job now. 

Please let me know if this solves your issue so I can close this and do another release of the code. 

Thanks,
Martin

**Comment by liuqian666** [comment]
Thank you very much! It helps me a lot !

**Comment by hoelzer** [comment]
Great, i will close this issue and generate a new release with this feature. Let me know if something else is needed

**Comment by hoelzer** [comment]
https://github.com/hoelzer/pocp/releases/tag/1.1.1
