### ISSUE TITLE
Conda issues when running the workflow

### ISSUE THREAD

**Issue by guosongjia** [hoelzer/pocp#22]
Dear Developers,\
Thanks for your software! I met with the following errors when running the commands using a nextflow environment created under conda env:\
\
(nextflow) [jiaguosong@dulab ~]$ nextflow run hoelzer/pocp -r 2.3.0 --help
N E X T F L O W  ~  version 0.24.2
Launching `hoelzer/pocp` [adoring_tesla] - revision: 092166e822 [2.3.0]
ERROR ~ Unable to parse config file: '/data/a/jiaguosong/.nextflow/assets/hoelzer/pocp/nextflow.config' 

  Compile failed for sources FixedSetSources[name='file:/data/a/jiaguosong/.nextflow/assets/hoelzer/pocp/configs/conda.config']. Cause: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
  file:/data/a/jiaguosong/.nextflow/assets/hoelzer/pocp/configs/conda.config: 2: you tried to assign a value to the class 'conda'. Do you have a script with this name?
   @ line 2, column 25.
         withLabel:     prokka  { conda = "$baseDir/envs/prokka.yaml" } 
                             ^
  
  file:/data/a/jiaguosong/.nextflow/assets/hoelzer/pocp/configs/conda.config: 3: you tried to assign a value to the class 'conda'. Do you have a script with this name?
   @ line 3, column 24.
         withLabel:     blast   { conda = "$baseDir/envs/blast.yaml" } 
                            ^
  
  file:/data/a/jiaguosong/.nextflow/assets/hoelzer/pocp/configs/conda.config: 4: you tried to assign a value to the class 'conda'. Do you have a script with this name?
   @ line 4, column 26.
         withLabel:     diamond { conda = "$baseDir/envs/diamond.yaml" } 
                              ^
  
  file:/data/a/jiaguosong/.nextflow/assets/hoelzer/pocp/configs/conda.config: 5: you tried to assign a value to the class 'conda'. Do you have a script with this name?
   @ line 5, column 23.
         withLabel:     pocp    { conda = "$baseDir/envs/diamond.yaml" } 
                           ^
  
  file:/data/a/jiaguosong/.nextflow/assets/hoelzer/pocp/configs/conda.config: 6: you tried to assign a value to the class 'conda'. Do you have a script with this name?
   @ line 6, column 23.
         withLabel:     ruby    { conda = "$baseDir/envs/ruby.yaml" } 
                           ^
  
  5 errors

 -- Check '.nextflow.log' file for details\
\
Could you please give me some advice to solve it?\
Best,\
Guo-Song

**Comment by hoelzer** [comment]
Hey, thanks for your interest in the tool!

Your nextflow version is very old. Please update nextflow and try again. 

You can install nextflow via conda, e.g.

```bash
conda create -n nf -c bioconda nextflow
conda activate nextflow
```

Or following the instructions at the nextflow.io webpage.

You should have at least version >21.x.x or smt similar

**Comment by guosongjia** [comment]
Thanks for your kind help!\
I removed my old nextflow env, created a new one, and successfully deployed the software.\
The same results were generated using the example data with the following commands:\
`nextflow run hoelzer/pocp -r 2.3.0 --proteins $HOME'/.nextflow/assets/hoelzer/pocp/example/*.faa' -profile local,conda`\
Best,\
Guo-Song

**Comment by hoelzer** [comment]
Perfect. Thanks for the info!
