### ISSUE TITLE
An emty resutl

### ISSUE THREAD

**Issue by Rathanin-github** [hoelzer/pocp#25]
Hi @hoelzer 

Thanks for a very nice tool to calculate the POCP. After installing, java, nextfow, I try to run: nextflow run hoelzer/pocp -r 2.3.4 --proteins *.faa -profile slurm,conda   but I get no output file containing the paiwise POCP. 

Here is the .log file: 

Nov-01 22:40:01.461 [main] DEBUG nextflow.cli.Launcher - $> nextflow run hoelzer/pocp -r 2.3.4 --proteins Cav_10DC88.faa Cga_08-1274-3.faa Cps_6BC.faa Ctr_D-UW-3-CX.faa
Nov-01 22:40:01.533 [main] DEBUG nextflow.cli.CmdRun - N E X T F L O W  ~  version 24.10.0
Nov-01 22:40:01.558 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/home/nc-bioinfo/.nextflow/plugins; core-plugins: nf-amazon@2.9.0,nf-azure@1.10.1,nf-cloudcache@0.4.2,nf-codecommit@0.2.2,nf-console@1.1.4,nf-google@1.15.2,nf-tower@1.9.3,nf-wave@1.7.2
Nov-01 22:40:01.581 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Nov-01 22:40:01.582 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Nov-01 22:40:01.586 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.12.0 in 'deployment' mode
Nov-01 22:40:01.599 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Nov-01 22:40:01.609 [main] DEBUG nextflow.scm.ProviderConfig - Using SCM config path: /home/nc-bioinfo/.nextflow/scm
Nov-01 22:40:02.193 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/nc-bioinfo/.nextflow/assets/hoelzer/pocp/.git/config; branch: null; remote: origin; url: https://github.com/hoelzer/pocp.git
Nov-01 22:40:02.222 [main] DEBUG nextflow.scm.RepositoryFactory - Found Git repository result: [RepositoryFactory]
Nov-01 22:40:02.233 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/nc-bioinfo/.nextflow/assets/hoelzer/pocp/.git/config; branch: null; remote: origin; url: https://github.com/hoelzer/pocp.git
Nov-01 22:40:03.245 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /home/nc-bioinfo/.nextflow/assets/hoelzer/pocp/nextflow.config
Nov-01 22:40:03.247 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/nc-bioinfo/.nextflow/assets/hoelzer/pocp/nextflow.config
Nov-01 22:40:03.253 [main] DEBUG n.secret.LocalSecretsProvider - Secrets store: /home/nc-bioinfo/.nextflow/secrets/store.json
Nov-01 22:40:03.255 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@69de5bed] - activable => nextflow.secret.LocalSecretsProvider@69de5bed
Nov-01 22:40:03.265 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Nov-01 22:40:03.464 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 from script declaration
Nov-01 22:40:03.465 [main] DEBUG nextflow.cli.CmdRun - Launching `https://github.com/hoelzer/pocp` [fabulous_perlman] DSL2 - revision: dbfb42a7f1 [2.3.4]
Nov-01 22:40:03.467 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Nov-01 22:40:03.467 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[]
Nov-01 22:40:03.517 [main] DEBUG nextflow.Session - Session UUID: 8fccfe06-e568-4a49-949a-156888a67bbb
Nov-01 22:40:03.518 [main] DEBUG nextflow.Session - Run name: fabulous_perlman
Nov-01 22:40:03.518 [main] DEBUG nextflow.Session - Executor pool size: 16
Nov-01 22:40:03.526 [main] DEBUG nextflow.file.FilePorter - File porter settings maxRetries=3; maxTransfers=50; pollTimeout=null
Nov-01 22:40:03.531 [main] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'FileTransfer' minSize=10; maxSize=48; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Nov-01 22:40:03.544 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 24.10.0 build 5928
  Created: 27-10-2024 18:36 UTC (28-10-2024 01:36 ICST)
  System: Linux 4.4.0-19041-Microsoft
  Runtime: Groovy 4.0.23 on OpenJDK 64-Bit Server VM 17.0.10+7
  Encoding: UTF-8 (UTF-8)
  Process: 12299@DESKTOP-7GO1EHN [127.0.1.1]
  CPUs: 16 - Mem: 63.9 GB (32.2 GB) - Swap: 116.4 GB (116.3 GB)
Nov-01 22:40:03.568 [main] DEBUG nextflow.Session - Work-dir: /mnt/d/bt_analysis/pocp/test/work [wslfs]
Nov-01 22:40:03.598 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Nov-01 22:40:03.607 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Nov-01 22:40:03.643 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Nov-01 22:40:03.652 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 17; maxThreads: 1000
Nov-01 22:40:03.808 [main] DEBUG nextflow.Session - Session start
Nov-01 22:40:04.126 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Nov-01 22:40:04.133 [main] INFO  nextflow.script.BaseScript -  
Nov-01 22:40:04.134 [main] INFO  nextflow.script.BaseScript - [32mProfile: standard[0m
Nov-01 22:40:04.135 [main] INFO  nextflow.script.BaseScript -  
Nov-01 22:40:04.135 [main] INFO  nextflow.script.BaseScript - [2mCurrent User: nc-bioinfo
Nov-01 22:40:04.136 [main] INFO  nextflow.script.BaseScript - Nextflow-version: 24.10.0
Nov-01 22:40:04.137 [main] INFO  nextflow.script.BaseScript - Starting time: 27-10-2024 18:36 UTC
Nov-01 22:40:04.137 [main] INFO  nextflow.script.BaseScript - Workdir location:
Nov-01 22:40:04.139 [main] INFO  nextflow.script.BaseScript -   /mnt/d/bt_analysis/pocp/test/work[0m
Nov-01 22:40:04.139 [main] INFO  nextflow.script.BaseScript -  
Nov-01 22:40:04.145 [main] INFO  nextflow.script.BaseScript - [32mPOCP-nf was executed in version '2.3.4' with default paramters according to the original publication by Qin et al. (2014). DIAMOND was used for protein alignments.
Nov-01 22:40:04.145 [main] INFO  nextflow.script.BaseScript - 
Nov-01 22:40:04.146 [main] INFO  nextflow.script.BaseScript - e-value:		1e-5
Nov-01 22:40:04.147 [main] INFO  nextflow.script.BaseScript - Sequence identity:	0.4
Nov-01 22:40:04.147 [main] INFO  nextflow.script.BaseScript - Alignment length:	0.5
Nov-01 22:40:04.148 [main] INFO  nextflow.script.BaseScript - [0m
Nov-01 22:40:04.609 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:diamond` matches labels `diamond` for process with name diamond
Nov-01 22:40:04.622 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: local
Nov-01 22:40:04.622 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Nov-01 22:40:04.628 [main] DEBUG nextflow.executor.Executor - [warm up] executor > local
Nov-01 22:40:04.632 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=16; memory=4 GB; capacity=16; pollInterval=100ms; dumpInterval=5m
Nov-01 22:40:04.634 [main] DEBUG n.processor.TaskPollingMonitor - >>> barrier register (monitor: local)
Nov-01 22:40:04.692 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:diamond` matches labels `diamond` for process with name pocp
Nov-01 22:40:04.693 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: local
Nov-01 22:40:04.693 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Nov-01 22:40:04.705 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:ruby` matches labels `ruby` for process with name pocp_matrix
Nov-01 22:40:04.706 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: local
Nov-01 22:40:04.706 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Nov-01 22:40:04.711 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:python` matches labels `python` for process with name plot
Nov-01 22:40:04.712 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: local
Nov-01 22:40:04.713 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Nov-01 22:40:04.716 [main] DEBUG nextflow.Session - Workflow process names [dsl2]: diamond, plot, pocp, pocp_matrix, prokka_single, prokka, blast
Nov-01 22:40:04.716 [main] DEBUG nextflow.Session - Igniting dataflow network (5)
Nov-01 22:40:04.721 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > diamond
Nov-01 22:40:04.721 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > pocp
Nov-01 22:40:04.722 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > pocp_matrix
Nov-01 22:40:04.722 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > plot
Nov-01 22:40:04.723 [main] DEBUG nextflow.script.ScriptRunner - Parsed script files:
  Script_f16af03bde31bac7: /home/nc-bioinfo/.nextflow/assets/hoelzer/pocp/./modules/prokka.nf
  Script_a41c397240753070: /home/nc-bioinfo/.nextflow/assets/hoelzer/pocp/./modules/pocp.nf
  Script_037b0cb9e67d5d97: /home/nc-bioinfo/.nextflow/assets/hoelzer/pocp/main.nf
  Script_984b806d1c3f9d52: /home/nc-bioinfo/.nextflow/assets/hoelzer/pocp/./modules/blast.nf
  Script_d70768f80f9ff96c: /home/nc-bioinfo/.nextflow/assets/hoelzer/pocp/./modules/plot.nf
  Script_b8c9aede3a8a6600: /home/nc-bioinfo/.nextflow/assets/hoelzer/pocp/./modules/diamond.nf
Nov-01 22:40:04.723 [main] DEBUG nextflow.script.ScriptRunner - > Awaiting termination 
Nov-01 22:40:04.723 [main] DEBUG nextflow.Session - Session await
Nov-01 22:40:04.739 [main] DEBUG nextflow.Session - Session await > all processes finished
Nov-01 22:40:04.749 [Task monitor] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: local) - terminating tasks monitor poll loop
Nov-01 22:40:04.749 [main] DEBUG nextflow.Session - Session await > all barriers passed
Nov-01 22:40:04.754 [main] DEBUG n.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=0; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=0ms; failedDuration=0ms; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=0; peakCpus=0; peakMemory=0; ]
Nov-01 22:40:04.888 [main] DEBUG nextflow.cache.CacheDB - Closing CacheDB done
Nov-01 22:40:04.915 [main] DEBUG nextflow.util.ThreadPoolManager - Thread pool 'FileTransfer' shutdown completed (hard=false)
Nov-01 22:40:04.916 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye

**Comment by hoelzer** [comment]
Hey @Rathanin-github did you solve the problem?

I think the problem might have been you missed the '...' for the input files:

```bash
nextflow run hoelzer/pocp -r 2.3.4 --proteins '*.faa' -profile slurm,conda
```

**Comment by Rathanin-github** [comment]
It works now I missed ' in the command. The corect command is: nextflow run hoelzer/pocp -r 2.3.4 --proteins '*.faa' -profile local,conda

**Comment by Rathanin-github** [comment]
Hi Hoelzer

I have already solved the problem.
Thank you so much for contributing a very nice tool for calculating POCP.

Best regards
Rathanin

**Comment by hoelzer** [comment]
Pleasure! Glad when it helps
