### ISSUE TITLE
Missing python in blast.yaml environment

### ISSUE THREAD

**Issue by michoug** [hoelzer/pocp#9]
Hi,
Sorry, I lost the error, but basically I ran the pipeline with `-profile local,mamba` and while running the pocp process, it indicated that `python` was not present. It seems that the environment file `blast.yaml` is not installing it
Best
Greg

**Comment by hoelzer** [comment]
Should be fixed with https://github.com/hoelzer/pocp/pull/12 bc of the switch to `diamond` instead of `blast` and making sure that python is now also in the conda/mamba env.
